name: demo
on:
    push:
        branches: datapack-format/*
    pull_request:
        branches: datapack-format/*

jobs:
    create_artifact:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'push' && github.ref || github.head_ref }}
            - uses: actions/upload-artifact@v4
              with:
                  name: demo-artifact
                  path: |
                      data/
                      LICENSE
                      pack.mcmeta
                      pack.png
