name: demo
on:
    push:
        branches:
          - 'datapack-format/*'
    pull_request:
        branches:
          - 'datapack-format/*'

jobs:
    demo:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.event_name == 'push' && github.ref || github.head_ref }}
            - uses: thedoctor0/zip-release@0.7.5
              with:
                type: zip
                filename: demo.zip
                exclusions: '*.git*'
            - uses: actions/upload-artifact@v4
              with:
                name: demo-artifact
                path: demo.zip
