name: Develop packing
on:
    push:
        branches: datapack-format/*
    pull_request:
        branches: datapack-format/*

jobs:
    create_artifact:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}
            - run: echo "ARTIFACT_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.ARTIFACT_NAME }}
                  path: |
                      data/
                      LICENSE
                      pack.mcmeta
                      pack.png
