name: demo
on: [push, pull_request]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo event_name: ${{ github.event_name }}
          echo ref: ${{ github.ref }}
          echo head_ref: ${{ github.head_ref }}
          echo base_ref: ${{ github.base_ref }}
